export const BLOCK_UI = 'BLOCK_UI';

export const LOAD_PROFILE_INFO = 'LOAD_PROFILE_INFO';
export const LOAD_AVAILS_MAPPING = 'LOAD_AVAILS_MAPPING';
export const LOAD_REPORTS = 'LOAD_REPORTS';

export const UPDATE_COLUMNS_SIZE = 'UPDATE_COLUMNS_SIZE';

export const SET_REPORT_NAME = 'SET_REPORT_NAME';

export const RIGHTS__LOAD_SELECT_LISTS = 'RIGHTS__LOAD_SELECT_LISTS';

export const DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH = 'DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH';
export const DASHBOARD_SEARCH_FORM__SET_ADVANCED_SEARCH_CRITERIA =
    'DASHBOARD_SEARCH_FORM__SET_ADVANCED_SEARCH_CRITERIA';
export const DASHBOARD_SEARCH_FORM__SET_SEARCH_CRITERIA = 'DASHBOARD_SEARCH_FORM__SET_SEARCH_CRITERIA';

export const AVAIL__SET_BULK_EXPORT = 'AVAIL__SET_BULK_EXPORT';
export const DASHBOARD_RESULT_PAGE__SORT = 'DASHBOARD_RESULT_PAGE__SORT';
export const DASHBOARD_RESULT_PAGE__LOADING = 'DASHBOARD_RESULT_PAGE__LOADING';
export const DASHBOARD_RESULT_PAGE__UPDATE_COLUMNS_ORDER = 'DASHBOARD_RESULT_PAGE__UPDATE_COLUMNS_ORDER';

export const METADATA_TITLE_LOAD_SESSION = 'METADATA_TITLE_LOAD_SESSION';

export const METADATA_TITLE_SEARCH_FORM__UPDATE_TEXT_SEARCH = 'METADATA_TITLE_SEARCH_FORM__UPDATE_TEXT_SEARCH';
export const METADATA_TITLE_SEARCH_FORM__SET_SEARCH_CRITERIA = 'METADATA_TITLE_SEARCH_FORM__SET_SEARCH_CRITERIA';
export const METADATA_TITLE_SEARCH_FORM__SHOW_SEARCH_RESULTS = 'METADATA_TITLE_SEARCH_FORM__SHOW_SEARCH_RESULTS';

export const METADATA_TITLE_RESULT_PAGE__UPDATE = 'METADATA_TITLE_RESULT_PAGE__UPDATE';
export const METADATA_TITLE_RESULT_PAGE__SORT = 'METADATA_TITLE_RESULT_PAGE__SORT';
export const METADATA_TITLE_RESULT_PAGE__LOADING = 'METADATA_TITLE_RESULT_PAGE__LOADING';
export const METADATA_TITLE_RESULT_PAGE__SELECT_ROW = 'METADATA_TITLE_RESULT_PAGE__SELECT_ROW';

export const METADATA_TITLE_UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB';
export const METADATA_TITLE_LOAD_PROFILE_INFO = 'METADATA_TITLE_LOAD_PROFILE_INFO';
export const METADATA_TITLE_LOAD_REPORTS = 'METADATA_TITLE_LOAD_REPORTS';
export const METADATA_TITLE_RESULT_PAGE__UPDATE_COLUMNS_ORDER = 'METADATA_TITLE_RESULT_PAGE__UPDATE_COLUMNS_ORDER';

export const TERRITORY_METADATA_ADD = 'TERRITORY_METADATA_ADD';
export const TERRITORY_METADATA_LOAD_BY_ID = 'TERRITORY_METADATA_LOAD_BY_ID';

export const METADATA_TITLE_CONFIG__LOAD = 'METADATA_TITLE_CONFIG__LOAD';

export const DOP_UPDATE_PROMOTED_RIGHTS = 'DOP_UPDATE_PROMOTED_RIGHTS';
export const DOP_UPDATE_PROMOTED_RIGHTS_FULL_DATA = 'DOP_UPDATE_PROMOTED_RIGHTS_FULL_DATA';
export const DOP_UPDATE_SELECTED_TERRITORIES = 'DOP_UPDATE_SELECTED_TERRITORIES';
export const DOP_UPDATE_USE_SELECTED_TERRITORIES = 'DOP_UPDATE_USE_SELECTED_TERRITORIES';
export const DOP_UPDATE_SELECTED_TERRITORIES_TAB = 'DOP_UPDATE_SELECTED_TERRITORIES_TAB';
export const DOP_UPDATE_RIGHTS_FILTER = 'DOP_UPDATE_RIGHTS_FILTER';

export const SET_LOCALE = 'SET_LOCALE';

export const MANUAL_RIGHT_ENTRY__SET_SELECTED_TAB = 'MANUAL_RIGHT_ENTRY__SET_SELECTED_TAB';
export const MANUAL_RIGHT_ENTRY__UPDATE_COLUMNS = 'MANUAL_RIGHT_ENTRY__UPDATE_COLUMNS';
export const MANUAL_RIGHT_ENTRY__SELECT_ROW = 'MANUAL_RIGHT_ENTRY__SELECT_ROW';
export const MANUAL_RIGHT_ENTRY__UPDATE = 'MANUAL_RIGHT_ENTRY__UPDATE';
export const MANUAL_RIGHT_ENTRY__LOADING = 'MANUAL_RIGHT_ENTRY__LOADING';
export const MANUAL_RIGHT_ENTRY__SORT = 'MANUAL_RIGHT_ENTRY__SORT';
