export const CREATE_RIGHT_MATCHING_COLUMN_DEFS = 'CREATE_RIGHT_MATCHING_COLUMN_DEFS';
export const STORE_RIGHT_MATCHING_COLUMN_DEFS = 'STORE_RIGHT_MATCHING_COLUMN_DEFS';

export const FETCH_FOCUSED_RIGHT = 'FETCH_FOCUSED_RIGHT';
export const FETCH_FOCUSED_RIGHT_REQUEST = 'FETCH_FOCUSED_RIGHT_REQUEST';
export const FETCH_FOCUSED_RIGHT_SUCCESS = 'FETCH_FOCUSED_RIGHT_SUCCESS';
export const FETCH_FOCUSED_RIGHT_ERROR = 'FETCH_FOCUSED_RIGHT_ERROR';

export const FETCH_RIGHT_MATCH_DATA_UNTIL_FIND_ID = 'FETCH_RIGHT_MATCH_DATA_UNTIL_FIND_ID';
export const FETCH_RIGHT_MATCH_DATA_UNTIL_FIND_ID_FAILED = 'FETCH_RIGHT_MATCH_DATA_UNTIL_FIND_ID_FAILED';
export const STORE_RIGHT_MATCH_DATA_WITH_IDS = 'STORE_RIGHT_MATCH_DATA_WITH_IDS';
export const CLEAN_STORED_RIGHT_MATCH_DATA_WITH_IDS = 'CLEAN_STORED_RIGHT_MATCH_DATA_WITH_IDS';