export const CREATE_RIGHT_MATCHING_COLUMN_DEFS = 'CREATE_RIGHT_MATCHING_COLUMN_DEFS';
export const STORE_RIGHT_MATCHING_COLUMN_DEFS = 'STORE_RIGHT_MATCHING_COLUMN_DEFS';

export const FETCH_RIGHT_MATCHING_PROVIDER = 'FETCH_RIGHT_MATCHING_PROVIDER';
export const FETCH_RIGHT_MATCHING_PROVIDER_REQUEST = 'FETCH_RIGHT_MATCHING_PROVIDER_REQUEST';
export const FETCH_RIGHT_MATCHING_PROVIDER_SUCCESS = 'FETCH_RIGHT_MATCHING_PROVIDER_SUCCESS';
export const FETCH_RIGHT_MATCHING_PROVIDER_ERROR = 'FETCH_RIGHT_MATCHING_PROVIDER_ERROR';

export const FETCH_AND_STORE_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA = 'FETCH_AND_STORE_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA';
export const FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_REQUEST = 'FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_REQUEST';
export const FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_SUCCESS = 'FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_SUCCESS';
export const FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_ERROR = 'FETCH_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA_ERROR';
export const STORE_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA = 'STORE_RIGHT_MATCHING_FIELD_SEARCH_CRITERIA';

export const FETCH_AND_STORE_FOCUSED_RIGHT = 'FETCH_AND_STORE_FOCUSED_RIGHT';
export const FETCH_FOCUSED_RIGHT_REQUEST = 'FETCH_FOCUSED_RIGHT_REQUEST';
export const FETCH_FOCUSED_RIGHT_SUCCESS = 'FETCH_FOCUSED_RIGHT_SUCCESS';
export const FETCH_FOCUSED_RIGHT_ERROR = 'FETCH_FOCUSED_RIGHT_ERROR';
export const STORE_FOCUSED_RIGHT = 'STORE_FOCUSED_RIGHT';
