export const CREATE_RIGHT_MATCHING_COLUMN_DEFS = 'CREATE_RIGHT_MATCHING_COLUMN_DEFS';
export const STORE_RIGHT_MATCHING_COLUMN_DEFS = 'STORE_RIGHT_MATCHING_COLUMN_DEFS';

export const FETCH_FOCUSED_RIGHT = 'FETCH_FOCUSED_RIGHT';
export const FETCH_FOCUSED_RIGHT_REQUEST = 'FETCH_FOCUSED_RIGHT_REQUEST';
export const FETCH_FOCUSED_RIGHT_SUCCESS = 'FETCH_FOCUSED_RIGHT_SUCCESS';
export const FETCH_FOCUSED_RIGHT_ERROR = 'FETCH_FOCUSED_RIGHT_ERROR';