export const FETCH_AND_STORE_RIGHT_HISTORY = 'FETCH_AND_STORE_RIGHT_HISTORY';
export const FETCH_RIGHT_HISTORY_REQUEST = 'FETCH_RIGHT_HISTORY_REQUEST';
export const FETCH_RIGHT_HISTORY_SUCCESS = 'FETCH_RIGHT_HISTORY_SUCCESS';
export const FETCH_RIGHT_HISTORY_ERROR = 'FETCH_RIGHT_HISTORY_ERROR';