export const METADATA_TITLE_TITLE_SECTION = 'Title';
export const METADATA_TITLE_CAST_N_CREW_SECTION = 'Cast & Crew';
export const METADATA_TITLE_RATINGS_SECTION = 'Ratings';
export const METADATA_TITLE_EXTERNAL_IDS_SECTION = 'External IDs';
export const METADATA_TITLE_EDITORIAL_SECTION = 'Editorial';
export const METADATA_TITLE_TERRITORIAL_SECTION = 'Territorial';
export const METADATA_TITLE_RIGHTS_SECTION = 'Rights';
export const METADATA_TITLE_SYNC_LOG_SECTION = 'Sync Log';

export const METADATA_TITLE_SECTIONS = [
    METADATA_TITLE_TITLE_SECTION,
    METADATA_TITLE_CAST_N_CREW_SECTION,
    METADATA_TITLE_RATINGS_SECTION,
    METADATA_TITLE_EXTERNAL_IDS_SECTION,
    METADATA_TITLE_EDITORIAL_SECTION,
    METADATA_TITLE_TERRITORIAL_SECTION,
    METADATA_TITLE_RIGHTS_SECTION,
    METADATA_TITLE_SYNC_LOG_SECTION,
];
