export const HANDLE_CONFIG_ENDPOINT_VALUES = 'HANDLE_CONFIG_ENDPOINT_VALUES';
export const HANDLE_CONFIG_ENDPOINT_SUCCESS = 'HANDLE_CONFIG_ENDPOINT_SUCCESS';
export const HANDLE_CONFIG_ENDPOINT_ERROR = 'HANDLE_CONFIG_ENDPOINT_ERROR';

export const storeConfigValues = payload => ({
    type: HANDLE_CONFIG_ENDPOINT_VALUES,
    payload,
});
