export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';
export const STORE_USER_ACCOUNT = 'STORE_USER_ACCOUNT';
export const STORE_TOKENS = 'STORE_TOKENS';
export const SET_SELECTED_TENANT_INFO = 'SET_SELECTED_TENANT_INFO';
