export const SET_DOP_TASKS_USER_DEFINED_GRID_STATE = 'SET_DOP_TASKS_USER_DEFINED_GRID_STATE';
export const GET_DOP_TASKS_OWNERS = 'GET_DOP_TASKS_POTENTIAL_OWNERS';
export const SET_OWNERS_LIST = 'SET_DOP_OWNERS_LIST';
