export const LOAD_PROFILE_INFO = "LOAD_PROFILE_INFO";

export const DASHBOARD_RESULT_PAGE_UPDATE = "DASHBOARD_RESULT_PAGE_UPDATE";
export const DASHBOARD_RESULT_PAGE_SORT = "DASHBOARD_RESULT_PAGE_SORT";