export const LOAD_PROFILE_INFO = 'LOAD_PROFILE_INFO';

export const DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH = 'DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH';
export const DASHBOARD_SEARCH_FORM__UPDATE_SEARCH_CRITERIA = 'DASHBOARD_SEARCH_FORM__UPDATE_SEARCH_CRITERIA';
export const DASHBOARD_SEARCH_FORM__USE_ADVANCED_SEARCH = 'DASHBOARD_SEARCH_FORM__USE_ADVANCED_SEARCH';

export const DASHBOARD_RESULT_PAGE__UPDATE = 'DASHBOARD_RESULT_PAGE__UPDATE';
export const DASHBOARD_RESULT_PAGE__SORT = 'DASHBOARD_RESULT_PAGE__SORT';
export const DASHBOARD_RESULT_PAGE__LOADING = 'DASHBOARD_RESULT_PAGE__LOADING';
export const DASHBOARD_RESULT_PAGE__SELECT_ROW = 'DASHBOARD_RESULT_PAGE__SELECT_ROW';