export const LOAD_PROFILE_INFO = 'LOAD_PROFILE_INFO';
export const LOAD_AVAILS_MAPPING = 'LOAD_AVAILS_MAPPING';
export const LOAD_REPORTS = 'LOAD_REPORTS';
export const SET_REPORT_NAME = 'SET_REPORT_NAME';
export const LOAD_SESSION='LOAD_SESSION';

export const DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH = 'DASHBOARD_SEARCH_FORM__UPDATE_TEXT_SEARCH';
export const DASHBOARD_SEARCH_FORM__UPDATE_ADVANCED_SEARCH_CRITERIA = 'DASHBOARD_SEARCH_FORM__UPDATE_ADVANCED_SEARCH_CRITERIA';
export const DASHBOARD_SEARCH_FORM__UPDATE_SEARCH_CRITERIA = 'DASHBOARD_SEARCH_FORM__UPDATE_SEARCH_CRITERIA';
export const DASHBOARD_SEARCH_FORM__USE_ADVANCED_SEARCH = 'DASHBOARD_SEARCH_FORM__USE_ADVANCED_SEARCH';

export const DASHBOARD_RESULT_PAGE__UPDATE = 'DASHBOARD_RESULT_PAGE__UPDATE';
export const DASHBOARD_RESULT_PAGE__SORT = 'DASHBOARD_RESULT_PAGE__SORT';
export const DASHBOARD_RESULT_PAGE__LOADING = 'DASHBOARD_RESULT_PAGE__LOADING';
export const DASHBOARD_RESULT_PAGE__SELECT_ROW = 'DASHBOARD_RESULT_PAGE__SELECT_ROW';