export const SAVE_FULFILLMENT_ORDER = 'SAVE_FULFILLMENT_ORDER';
export const SAVE_FULFILLMENT_ORDER_REQUEST = 'SAVE_FULFILLMENT_ORDER_REQUEST';
export const SAVE_FULFILLMENT_ORDER_SUCCESS = 'SAVE_FULFILLMENT_ORDER_SUCCESS';
export const SAVE_FULFILLMENT_ORDER_ERROR = 'SAVE_FULFILLMENT_ORDER_ERROR';