export const REPLAY_EVENT = 'REPLAY_EVENT';
export const REPLAY_EVENT_REQUEST = 'REPLAY_EVENT_REQUEST';
export const REPLAY_EVENT_SUCCESS = 'REPLAY_EVENT_SUCCESS';
export const REPLAY_EVENT_ERROR = 'REPLAY_EVENT_ERROR';