export const REPLAY_EVENT = 'REPLAY_EVENT';
export const REPLAY_EVENT_REQUEST = 'REPLAY_EVENT_REQUEST';
export const REPLAY_EVENT_SUCCESS = 'REPLAY_EVENT_SUCCESS';
export const REPLAY_EVENT_ERROR = 'REPLAY_EVENT_ERROR';
export const REPLICATE_EVENT = 'REPLICATE_EVENT';
export const REPLICATE_EVENT_REQUEST = 'REPLICATE_EVENT_REQUEST';
export const REPLICATE_EVENT_SUCCESS = 'REPLICATE_EVENT_SUCCESS';
export const REPLICATE_EVENT_ERROR = 'REPLICATE_EVENT_ERROR';
