export const FETCH_AND_STORE_TITLE = 'FETCH_AND_STORE_TITLE';
export const FETCH_TITLE_REQUEST = 'FETCH_TITLE_REQUEST';
export const FETCH_TITLE_SUCCESS = 'FETCH_TITLE_SUCCESS';
export const FETCH_TITLE_ERROR = 'FETCH_TITLE_ERROR';
export const STORE_TITLE = 'STORE_TITLE';
