export const GET_SELECT_VALUES = 'GET_SELECT_VALUES';
export const STORE_SELECT_VALUES = 'STORE_SELECT_VALUES';
export const FETCH_SELECT_VALUES_REQUEST = 'FETCH_SELECT_VALUES_REQUEST';
export const FETCH_SELECT_VALUES_SUCCESS = 'FETCH_SELECT_VALUES_SUCCESS';
export const FETCH_SELECT_VALUES_ERROR = 'FETCH_SELECT_VALUES_ERROR';
export const SAVING = 'SAVING';
