export const EXCLUDED_ATTRIBUTES = ['PROJECT_NAME'];
export const DOP_PROJECT_STATUS_COMPLETED = 'COMPLETED';
export const DOP_PROJECT_STATUS_IN_PROGRESS = 'CIN PROGRESS';
export const DOP_PROJECT_STATUS_NOT_STARTED = 'BNOT STARTED';
export const DOP_PROJECT_STATUS_CANCELLED = 'CANCELLED';
export const EXCLUDED_STATUSES = [DOP_PROJECT_STATUS_CANCELLED, DOP_PROJECT_STATUS_COMPLETED];
