export default {
  FETCH_INGESTS: 'FETCH_INGESTS',
  FETCH_INGESTS_SUCCESS: 'FETCH_INGESTS_SUCCESS',
  FETCH_INGESTS_ERROR: 'FETCH_INGESTS_ERROR',
  FETCH_NEXT_PAGE: 'FETCH_INGESTS_NEXT_PAGE',
  FETCH_NEXT_PAGE_SUCCESS: 'FETCH_INGESTS_NEXT_PAGE_SUCCESS',
  FETCH_NEXT_PAGE_ERROR: 'FETCH_NEXT_PAGE_ERROR',
  FILTER_RIGHTS_BY_STATUS : 'RIGHTS_REPOSITORY_FILTER_BY_STATUS'
};