export default {
  FETCH_AVAILS: 'FETCH_AVAILS',
  FETCH_AVAILS_SUCCESS: 'FETCH_AVAILS_SUCCESS',
  FETCH_AVAILS_ERROR: 'FETCH_AVAILS_ERROR',
  FETCH_NEXT_PAGE: 'FETCH_AVAILS_NEXT_PAGE',
  FETCH_NEXT_PAGE_SUCCESS: 'FETCH_AVAILS_NEXT_PAGE_SUCCESS',
  FETCH_NEXT_PAGE_ERROR: 'FETCH_NEXT_PAGE_ERROR'
};