export const GET_TITLE = 'GET_TITLE';
export const GET_TITLE_SUCCESS = 'GET_TITLE_SUCCESS';
export const GET_TITLE_ERROR = 'GET_TITLE_ERROR';

export const GET_EXTERNAL_IDS = 'GET_EXTERNAL_IDS';
export const GET_EXTERNAL_IDS_SUCCESS = 'GET_EXTERNAL_IDS_SUCCESS';
export const GET_EXTERNAL_IDS_ERROR = 'GET_EXTERNAL_IDS_ERROR';

export const GET_TERRITORY_METADATA = 'GET_TERRITORY_METADATA';
export const GET_TERRITORY_METADATA_SUCCESS = 'GET_TERRITORY_METADATA_SUCCESS';
export const GET_TERRITORY_METADATA_ERROR = 'GET_TERRITORY_METADATA_ERROR';

export const GET_EDITORIAL_METADATA = 'GET_EDITORIAL_METADATA';
export const GET_EDITORIAL_METADATA_SUCCESS = 'GET_EDITORIAL_METADATA_SUCCESS';
export const GET_EDITORIAL_METADATA_ERROR = 'GET_EDITORIAL_METADATA_ERROR';

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_TITLE_SUCCESS = 'UPDATE_TITLE_SUCCESS';
export const UPDATE_TITLE_ERROR = 'UPDATE_TITLE_ERROR';

export const SYNC_TITLE = 'SYNC_TITLE';
export const PUBLISH_TITLE = 'PUBLISH_TITLE';
