export default {
    COMPLETED: 'Completed',
    COMPLETE: 'Complete',
    PENDING: 'Pending',
    FAILED: 'Failed',
    MANUAL: 'Manual',
    IN_PROGRESS: 'In Progress',
    ON_HOLD: 'On Hold',
    READY: 'Ready',
    NOT_STARTED: 'Not Started',
    FO_NOT_STARTED: 'Not Started',
    FO_IN_PROGRESS: 'In Progress',
    FO_ON_HOLD: 'On Hold',
    FO_COMPLETE: 'Complete',
    FO_CANCELLED: 'Cancelled',
    FO_FAILED: 'Failed',
    FO_ACCEPTED: 'Accepted',
};
