export const FETCH_FOCUSED_RIGHT = 'TITLE_MATCHING_FETCH_FOCUSED_RIGHT';
export const FETCH_FOCUSED_RIGHT_REQUEST = 'TITLE_MATCHING_FETCH_FOCUSED_RIGHT_REQUEST';
export const FETCH_FOCUSED_RIGHT_SUCCESS = 'TITLE_MATCHING_FETCH_FOCUSED_RIGHT_SUCCESS';
export const FETCH_FOCUSED_RIGHT_ERROR = 'TITLE_MATCHING_FETCH_FOCUSED_RIGHT_ERROR';