export const RIGHTS_TAB = 'Rights';
export const RIGHTS_SELECTED_TAB = 'Selected';
export const PRE_PLAN_TAB = 'Pre-Plan';
export const SELECTED_FOR_PLANNING_TAB = 'Selected for Planning';
export const CREATE_NEW_RIGHT = 'Create New Right';
export const DEFAULT_PAGE_SIZE = 200;
export const PREPLAN_REPORT = 'Pre_Plan_Report';
export const SELECTED_FOR_PLANNING_REPORT = 'Selected_For_Planning_Report';
export const IN_PROGRESS = 'IN PROGRESS';
