export const SET_SELECTED_RIGHTS = 'SET_SELECTED_RIGHTS';
export const SET_PREPLAN_RIGHTS = 'SET_PREPLAN_RIGHTS';
export const ADD_RIGHTS_FILTER = 'ADD_RIGHTS_FILTER';
export const ADD_RIGHTS_FILTER_SUCCESS = 'ADD_RIGHTS_FILTER_SUCCESS';
export const ADD_RIGHTS_FILTER_ERROR = 'ADD_RIGHTS_FILTER_ERROR';
export const REMOVE_RIGHTS_FILTER = 'REMOVE_RIGHTS_FILTER';
export const SET_RIGHTS_FILTER = 'SET_RIGHTS_FILTER';
