export const UPLOAD_INGEST = 'UPLOAD_INGEST_FILES';
export const SAVE_COMBINED_RIGHT = 'SAVE_COMBINED_RIGHT';
export const REPLAY_EVENT = 'REPLAY_EVENT';
export const REPLICATE_EVENT = 'REPLICATE_EVENT';
export const TITLES_RECONCILE = 'TITLES_RECONCILE_REQUEST';
export const SAVE_FULFILLMENT_ORDER = 'SAVE_FULFILLMENT_ORDER';
export const TITLE_MATCHING_MERGE_TITLES = 'TITLE_MATCHING_MERGE_TITLES_REQUEST';
export const UPLOAD_ARTWORK = 'UPLOAD_ARTWORK';
