export const FETCH_CONFIG_API_ENDPOINTS = 'FETCH_CONFIG_API_ENDPOINTS';
export const FETCH_CONFIG_API_ENDPOINTS_REQUEST = 'FETCH_CONFIG_API_ENDPOINTS_REQUEST';
export const FETCH_CONFIG_API_ENDPOINTS_SUCCESS = 'FETCH_CONFIG_API_ENDPOINTS_SUCCESS';
export const FETCH_CONFIG_API_ENDPOINTS_ERROR = 'FETCH_CONFIG_API_ENDPOINTS_ERROR';
export const STORE_CONFIG_API_ENDPOINTS = 'STORE_CONFIG_API_ENDPOINTS';
