export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const STORE_AUTH_CREDENTIALS = 'STORE_AUTH_CREDENTIALS';
export const STORE_AUTH_CREDENTIALS_REQUEST = 'STORE_AUTH_CREDENTIALS_REQUEST';
export const STORE_AUTH_CREDENTIALS_SUCCESS = 'STORE_AUTH_CREDENTIALS_SUCCESS';
export const STORE_AUTH_CREDENTIALS_ERROR = 'STORE_AUTH_CREDENTIALS_ERROR';

